<?php

return [
    'bus' => array_filter([
        [
            'operator_id'      => env('COMPANY_1_OPERATOR_ID'),
            'operator'         => env('COMPANY_1_NAME'),
            'User_Id'          => env('COMPANY_1_USER_ID'),
            'username'         => env('COMPANY_1_USERNAME'),
            'password'         => env('COMPANY_1_PASSWORD'),
            'terminal_name'    => env('COMPANY_1_TERMINAL_NAME'),
            'terminal_id'      => env('COMPANY_1_TERMINAL_ID'),
            'api_url'          => env('COMPANY_1_API_URL'),
            'fare_api_url'     => env('COMPANY_1_FARE_URL'),
            'seat_api_url'     => env('COMPANY_1_SEAT_URL'),
            'hold_api_url'     => env('COMPANY_1_HOLD_URL'),
            'unhold_api_url'   => env('COMPANY_1_UNHOLD_URL'),
            'terminal_api_url' => env('COMPANY_1_TERMINAL_URL'),
            'update_seat'      => env('COMPANY_1_UPDATE_SEAT_URL'),
            'refund_api'       => env('COMPANY_1_REFUND_URL'),
        ],
        [
            'operator_id'      => env('COMPANY_2_OPERATOR_ID'),
            'operator'         => env('COMPANY_2_NAME'),
            'User_Id'          => env('COMPANY_2_USER_ID'),
            'username'         => env('COMPANY_2_USERNAME'),
            'password'         => env('COMPANY_2_PASSWORD'),
            'terminal_name'    => env('COMPANY_2_TERMINAL_NAME'),
            'terminal_id'      => env('COMPANY_2_TERMINAL_ID'),
            'api_url'          => env('COMPANY_2_API_URL'),
            'fare_api_url'     => env('COMPANY_2_FARE_URL'),
            'seat_api_url'     => env('COMPANY_2_SEAT_URL'),
            'hold_api_url'     => env('COMPANY_2_HOLD_URL'),
            'unhold_api_url'   => env('COMPANY_2_UNHOLD_URL'),
            'terminal_api_url' => env('COMPANY_2_TERMINAL_URL'),
            'update_seat'      => env('COMPANY_2_UPDATE_SEAT_URL'),
            'refund_api'       => env('COMPANY_2_REFUND_URL'),
        ],
        [
            'operator_id'      => env('COMPANY_3_OPERATOR_ID'),
            'operator'         => env('COMPANY_3_NAME'),
            'User_Id'          => env('COMPANY_3_USER_ID'),
            'username'         => env('COMPANY_3_USERNAME'),
            'password'         => env('COMPANY_3_PASSWORD'),
            'terminal_name'    => env('COMPANY_3_TERMINAL_NAME'),
            'terminal_id'      => env('COMPANY_3_TERMINAL_ID'),
            'api_url'          => env('COMPANY_3_API_URL'),
            'fare_api_url'     => env('COMPANY_3_FARE_URL'),
            'seat_api_url'     => env('COMPANY_3_SEAT_URL'),
            'hold_api_url'     => env('COMPANY_3_HOLD_URL'),
            'unhold_api_url'   => env('COMPANY_3_UNHOLD_URL'),
            'terminal_api_url' => env('COMPANY_3_TERMINAL_URL'),
            'update_seat'      => env('COMPANY_3_UPDATE_SEAT_URL'),
            'refund_api'       => env('COMPANY_3_REFUND_URL'),
        ],
    ], fn($c) => !empty($c['operator_id']) && !empty($c['api_url'])),
];
